apiVersion: v1
kind: ServiceAccount
metadata:
  name: gadget-ca-job
  namespace: gadget
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gadget-ca-job
  namespace: gadget
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "create", "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gadget-ca-job
  namespace: gadget
subjects:
  - kind: ServiceAccount
    name: gadget-ca-job
    namespace: gadget
roleRef:
  kind: Role
  name: gadget-ca-job
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: gadget-ca-job
  namespace: gadget
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: gadget-ca-job
    spec:
      serviceAccountName: gadget-ca-job
      restartPolicy: Never
      containers:
        - name: get-cert
          image: ghcr.io/inspektor-gadget/ca-job:latest
          imagePullPolicy: Never
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
