// Copyright 2019-2022 The Inspektor Gadget authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package trace

import (
	"fmt"
	"strconv"
	"strings"

	commonutils "github.com/kinvolk/inspektor-gadget/cmd/common/utils"
	"github.com/kinvolk/inspektor-gadget/cmd/kubectl-gadget/utils"
	"github.com/kinvolk/inspektor-gadget/pkg/gadgets/bindsnoop/types"
	"github.com/spf13/cobra"
)

type BindParser struct {
	commonutils.BaseParser
}

func newBindCmd() *cobra.Command {
	commonFlags := &utils.CommonFlags{
		OutputConfig: commonutils.OutputConfig{
			// The columns that will be used in case the user does not specify
			// which specific columns they want to print.
			CustomColumns: []string{
				"node",
				"namespace",
				"pod",
				"container",
				"pid",
				"comm",
				"proto",
				"addr",
				"port",
				"opts",
				"if",
			},
		},
	}

	var (
		// flags
		targetPid    uint
		targetPorts  []uint
		ignoreErrors bool
	)

	cmd := &cobra.Command{
		Use:   "bind",
		Short: "Trace the kernel functions performing socket binding",
		RunE: func(cmd *cobra.Command, args []string) error {
			portsStringSlice := []string{}
			for _, port := range targetPorts {
				portsStringSlice = append(portsStringSlice, strconv.FormatUint(uint64(port), 10))
			}

			bindGadget := &TraceGadget[types.Event]{
				name:        "bindsnoop",
				commonFlags: commonFlags,
				parser:      NewBindParser(&commonFlags.OutputConfig),
				params: map[string]string{
					"pid":           strconv.FormatUint(uint64(targetPid), 10),
					"ports":         strings.Join(portsStringSlice, ","),
					"ignore_errors": strconv.FormatBool(ignoreErrors),
				},
			}

			return bindGadget.Run()
		},
	}

	cmd.PersistentFlags().UintVarP(
		&targetPid,
		"pid",
		"",
		0,
		"Show only bind events generated by this particular PID",
	)
	cmd.PersistentFlags().UintSliceVarP(
		&targetPorts,
		"ports",
		"P",
		[]uint{},
		"Trace only bind events involving these ports",
	)
	cmd.PersistentFlags().BoolVarP(
		&ignoreErrors,
		"ignore-errors",
		"i",
		true,
		"Show only events where the bind succeeded",
	)

	utils.AddCommonFlags(cmd, commonFlags)

	return cmd
}

func NewBindParser(outputConfig *commonutils.OutputConfig) TraceParser[types.Event] {
	columnsWidth := map[string]int{
		"node":      -16,
		"namespace": -16,
		"pod":       -30,
		"container": -16,
		"pid":       -7,
		"comm":      -16,
		"proto":     -6,
		"addr":      -16,
		"port":      -7,
		"opts":      -7,
		"if":        -7,
	}

	return &BindParser{
		BaseParser: commonutils.BaseParser{
			ColumnsWidth: columnsWidth,
			OutputConfig: outputConfig,
		},
	}
}

func (p *BindParser) TransformEvent(event *types.Event) string {
	var sb strings.Builder

	for _, col := range p.OutputConfig.CustomColumns {
		switch col {
		case "node":
			sb.WriteString(fmt.Sprintf("%*s", p.ColumnsWidth[col], event.Node))
		case "namespace":
			sb.WriteString(fmt.Sprintf("%*s", p.ColumnsWidth[col], event.Namespace))
		case "pod":
			sb.WriteString(fmt.Sprintf("%*s", p.ColumnsWidth[col], event.Pod))
		case "container":
			sb.WriteString(fmt.Sprintf("%*s", p.ColumnsWidth[col], event.Container))
		case "pid":
			sb.WriteString(fmt.Sprintf("%*d", p.ColumnsWidth[col], event.Pid))
		case "comm":
			sb.WriteString(fmt.Sprintf("%*s", p.ColumnsWidth[col], event.Comm))
		case "proto":
			sb.WriteString(fmt.Sprintf("%*s", p.ColumnsWidth[col], event.Protocol))
		case "addr":
			sb.WriteString(fmt.Sprintf("%*s", p.ColumnsWidth[col], event.Addr))
		case "port":
			sb.WriteString(fmt.Sprintf("%*d", p.ColumnsWidth[col], event.Port))
		case "opts":
			sb.WriteString(fmt.Sprintf("%*s", p.ColumnsWidth[col], event.Options))
		case "if":
			sb.WriteString(fmt.Sprintf("%*s", p.ColumnsWidth[col], event.Interface))
		}

		// Needed when field is larger than the predefined columnsWidth.
		sb.WriteRune(' ')
	}

	return sb.String()
}
