changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Dependencies updates
      labels:
        - dependencies
        - go
    - title: CI updates
      labels:
        - dependencies
        - github_actions
    - title: Other Changes
      labels:
        - "*"
