version: "2"
run:
  go: 1.24.2
  build-tags:
    - docs
linters:
  default: none
  enable:
    - errorlint
    - staticcheck
  settings:
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    rules:
      # Ignore check: Packages must have a package comment
      - linters:
          - staticcheck
        text: 'ST1000: at least one file in a package should have a package comment'
      # Ignore rule about ID vs Id: https://github.com/golang/lint/issues/89
      - linters:
          - staticcheck
        text: 'ST1003:'
      - linters:
          - staticcheck
        text: Switch to image-based gadgets instead
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/inspektor-gadget/inspektor-gadget
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
