#ifndef GADGET_SECCOMP_COMMON_H
#define GADGET_SECCOMP_COMMON_H

// Please update these values also in ../tracer.go
#define SYSCALLS_COUNT 500
#define SYSCALLS_MAP_VALUE_FOOTER_SIZE 1
#define SYSCALLS_MAP_VALUE_SIZE \
	(SYSCALLS_COUNT + SYSCALLS_MAP_VALUE_FOOTER_SIZE)

#endif
