// Copyright 2022 The Inspektor Gadget authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package trace

import (
	"fmt"
	"math"

	"github.com/spf13/cobra"

	commonutils "github.com/kinvolk/inspektor-gadget/cmd/common/utils"
	bindTypes "github.com/kinvolk/inspektor-gadget/pkg/gadgets/trace/bind/types"
)

type BindFlags struct {
	TargetPid    int32
	IgnoreErrors bool
	TargetPorts  []uint

	// It is necessary because pflag doesn't support []uint16 flags.
	ValidatedTargetPorts []uint16
}

func newBindParser(outputConfig *commonutils.OutputConfig, options ...commonutils.Option) TraceParser[bindTypes.Event] {
	return commonutils.NewGadgetParser(outputConfig, bindTypes.MustGetColumns(), options...)
}

func NewBindParserWithK8sInfo(outputConfig *commonutils.OutputConfig) TraceParser[bindTypes.Event] {
	return newBindParser(outputConfig, commonutils.WithMetadataTag(commonutils.KubernetesTag))
}

func NewBindParserWithRuntimeInfo(outputConfig *commonutils.OutputConfig) TraceParser[bindTypes.Event] {
	return newBindParser(outputConfig, commonutils.WithMetadataTag(commonutils.ContainerRuntimeTag))
}

func NewBindParser(outputConfig *commonutils.OutputConfig) TraceParser[bindTypes.Event] {
	return newBindParser(outputConfig)
}

func NewBindCmd(runCmd func(*cobra.Command, []string) error, flags *BindFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "bind",
		Short: "Trace the kernel functions performing socket binding",
		PreRunE: func(cmd *cobra.Command, args []string) error {
			flags.ValidatedTargetPorts = make([]uint16, len(flags.TargetPorts))
			for _, port := range flags.TargetPorts {
				if port == 0 || port > math.MaxUint16 {
					return commonutils.WrapInErrInvalidArg("--ports",
						fmt.Errorf("invalid port. Valid range: 1-%d", math.MaxUint16))
				}

				flags.ValidatedTargetPorts = append(flags.ValidatedTargetPorts, uint16(port))
			}
			return nil
		},
		RunE: runCmd,
	}

	cmd.PersistentFlags().Int32VarP(
		&flags.TargetPid,
		"pid",
		"",
		0,
		"Show only bind events generated by this particular PID",
	)
	cmd.PersistentFlags().UintSliceVarP(
		&flags.TargetPorts,
		"ports",
		"P",
		[]uint{},
		"Trace only bind events involving these ports",
	)
	cmd.PersistentFlags().BoolVarP(
		&flags.IgnoreErrors,
		"ignore-errors",
		"i",
		true,
		"Show only events where the bind succeeded",
	)

	return cmd
}
