// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64
// +build 386 amd64 amd64p32 arm arm64 mips64le mips64p32le mipsle ppc64le riscv64

package tracer

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTcpconnect returns the embedded CollectionSpec for tcpconnect.
func loadTcpconnect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpconnectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpconnect: %w", err)
	}

	return spec, err
}

// loadTcpconnectObjects loads tcpconnect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//     *tcpconnectObjects
//     *tcpconnectPrograms
//     *tcpconnectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpconnectObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpconnect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpconnectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpconnectSpecs struct {
	tcpconnectProgramSpecs
	tcpconnectMapSpecs
}

// tcpconnectSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpconnectProgramSpecs struct {
	TcpV4Connect    *ebpf.ProgramSpec `ebpf:"tcp_v4_connect"`
	TcpV4ConnectRet *ebpf.ProgramSpec `ebpf:"tcp_v4_connect_ret"`
	TcpV6Connect    *ebpf.ProgramSpec `ebpf:"tcp_v6_connect"`
	TcpV6ConnectRet *ebpf.ProgramSpec `ebpf:"tcp_v6_connect_ret"`
}

// tcpconnectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpconnectMapSpecs struct {
	Events     *ebpf.MapSpec `ebpf:"events"`
	Ipv4Count  *ebpf.MapSpec `ebpf:"ipv4_count"`
	Ipv6Count  *ebpf.MapSpec `ebpf:"ipv6_count"`
	MountNsSet *ebpf.MapSpec `ebpf:"mount_ns_set"`
	Sockets    *ebpf.MapSpec `ebpf:"sockets"`
}

// tcpconnectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpconnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpconnectObjects struct {
	tcpconnectPrograms
	tcpconnectMaps
}

func (o *tcpconnectObjects) Close() error {
	return _TcpconnectClose(
		&o.tcpconnectPrograms,
		&o.tcpconnectMaps,
	)
}

// tcpconnectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpconnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpconnectMaps struct {
	Events     *ebpf.Map `ebpf:"events"`
	Ipv4Count  *ebpf.Map `ebpf:"ipv4_count"`
	Ipv6Count  *ebpf.Map `ebpf:"ipv6_count"`
	MountNsSet *ebpf.Map `ebpf:"mount_ns_set"`
	Sockets    *ebpf.Map `ebpf:"sockets"`
}

func (m *tcpconnectMaps) Close() error {
	return _TcpconnectClose(
		m.Events,
		m.Ipv4Count,
		m.Ipv6Count,
		m.MountNsSet,
		m.Sockets,
	)
}

// tcpconnectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpconnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpconnectPrograms struct {
	TcpV4Connect    *ebpf.Program `ebpf:"tcp_v4_connect"`
	TcpV4ConnectRet *ebpf.Program `ebpf:"tcp_v4_connect_ret"`
	TcpV6Connect    *ebpf.Program `ebpf:"tcp_v6_connect"`
	TcpV6ConnectRet *ebpf.Program `ebpf:"tcp_v6_connect_ret"`
}

func (p *tcpconnectPrograms) Close() error {
	return _TcpconnectClose(
		p.TcpV4Connect,
		p.TcpV4ConnectRet,
		p.TcpV6Connect,
		p.TcpV6ConnectRet,
	)
}

func _TcpconnectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//go:embed tcpconnect_bpfel.o
var _TcpconnectBytes []byte
