name: "Sign the OCI artifact"
description: "Sign the OCI artifact given as argument with cosign using the provided private key."

inputs:
  password:
    description: "Private key password"
    required: true
  private_key:
    description: "Private key to sign the OCI artifact"
    required: true
  oci_artifact:
    description: "The OCI artifact to sign"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
    - name: Sign the OCI artifact
      env:
        COSIGN_PASSWORD: '${{ inputs.password }}'
        COSIGN_PRIVATE_KEY: '${{ inputs.private_key }}'
        OCI_ARTIFACT: '${{ inputs.oci_artifact }}'
      shell: bash
      run: |
        # Force using legacy .sig format.
        # TODO Switch to bundle format.
        cosign sign --new-bundle-format=false --use-signing-config=false --key env://COSIGN_PRIVATE_KEY --yes --recursive "${OCI_ARTIFACT}"
