// Copyright 2019-2021 The Inspektor Gadget authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package top

import (
	"encoding/json"
	"fmt"
	"os"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/spf13/cobra"
	"golang.org/x/term"

	"github.com/kinvolk/inspektor-gadget/cmd/kubectl-gadget/utils"
	"github.com/kinvolk/inspektor-gadget/pkg/gadgets/tcptop/types"
)

var nodeTCPStats map[string][]types.Stats

var (
	// flags
	tcpSortBy      types.SortBy
	tcpFilteredPid uint
	tcpFamily      uint
)

var tcpCmd = &cobra.Command{
	Use:   fmt.Sprintf("tcp [interval=%d]", types.IntervalDefault),
	Short: "Trace TCP connection",
	RunE: func(cmd *cobra.Command, args []string) error {
		var err error

		nodeTCPStats = make(map[string][]types.Stats)

		if len(args) == 1 {
			outputInterval, err = strconv.Atoi(args[0])
			if err != nil {
				return utils.WrapInErrInvalidArg("interval", fmt.Errorf("%q is not a valid value", args[0]))
			}
		} else {
			outputInterval = types.IntervalDefault
		}

		parameters := map[string]string{
			types.MaxRowsParam:  strconv.Itoa(maxRows),
			types.IntervalParam: strconv.Itoa(outputInterval),
			types.SortByParam:   sortBy,
		}

		if tcpFamily != 0 {
			parameters[types.FamilyParam] = strconv.FormatUint(uint64(tcpFamily), 10)
		}

		if tcpFilteredPid != 0 {
			parameters[types.PidParam] = strconv.FormatUint(uint64(tcpFilteredPid), 10)
		}

		config := &utils.TraceConfig{
			GadgetName:       "tcptop",
			Operation:        "start",
			TraceOutputMode:  "Stream",
			TraceOutputState: "Started",
			CommonFlags:      &params,
			Parameters:       parameters,
		}

		// only wants to run for a given amount of time and print
		// that result.
		singleShot := params.Timeout == outputInterval

		// start print loop if this is not a "single shoot" operation
		if singleShot {
			tcpPrintHeader()
		} else {
			tcpStartPrintLoop()
		}

		if err := utils.RunTraceStreamCallback(config, tcpCallback); err != nil {
			return fmt.Errorf("error running trace: %w", err)
		}

		if singleShot {
			tcpPrintEvents()
		}

		return nil
	},
	SilenceUsage: true,
	PreRunE: func(cmd *cobra.Command, args []string) error {
		var err error
		tcpSortBy, err = types.ParseSortBy(sortBy)
		if err != nil {
			return err
		}

		return nil
	},
	Args: cobra.MaximumNArgs(1),
}

func init() {
	tcpCmd.PersistentFlags().UintVarP(
		&tcpFilteredPid,
		"pid",
		"",
		0,
		"Show only TCP events generated by this particular PID",
	)
	tcpCmd.PersistentFlags().UintVarP(
		&tcpFamily,
		"family",
		"f",
		0,
		"Show only TCP events for this IP version: either 4 or 6 (by default all will be printed)",
	)

	addTopCommand(tcpCmd, types.MaxRowsDefault, types.SortBySlice)
}

func tcpCallback(line string, node string) {
	mutex.Lock()
	defer mutex.Unlock()

	var event types.Event

	if err := json.Unmarshal([]byte(line), &event); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %s", utils.WrapInErrUnmarshalOutput(err, line))
		return
	}

	if event.Error != "" {
		fmt.Fprintf(os.Stderr, "Error: failed on node %q: %s", event.Node, event.Error)
		return
	}

	nodeTCPStats[node] = event.Stats
}

func tcpStartPrintLoop() {
	go func() {
		ticker := time.NewTicker(time.Duration(outputInterval) * time.Second)
		tcpPrintHeader()
		for {
			_ = <-ticker.C
			tcpPrintHeader()
			tcpPrintEvents()
		}
	}()
}

func tcpPrintHeader() {
	switch params.OutputMode {
	case utils.OutputModeColumns:
		if term.IsTerminal(int(os.Stdout.Fd())) {
			utils.ClearScreen()
		} else {
			fmt.Println("")
		}
		fmt.Printf("%-16s %-16s %-16s %-16s %-7s %-16s %-3s %-51s %-51s %-7s %s\n",
			"NODE", "NAMESPACE", "POD", "CONTAINER",
			"PID", "COMM", "IPv", "LADDR", "RADDR", "RX_KB", "TX_KB")
	case utils.OutputModeCustomColumns:
		if term.IsTerminal(int(os.Stdout.Fd())) {
			utils.ClearScreen()
		} else {
			fmt.Println("")
		}
		fmt.Println(tcpGetCustomColsHeaders(params.CustomColumns))
	}
}

func tcpPrintEvents() {
	// sort and print events
	mutex.Lock()

	stats := []types.Stats{}
	for _, stat := range nodeTCPStats {
		stats = append(stats, stat...)
	}
	nodeTCPStats = make(map[string][]types.Stats)

	mutex.Unlock()

	types.SortStats(stats, tcpSortBy)

	switch params.OutputMode {
	case utils.OutputModeColumns:
		for idx, event := range stats {
			if idx == maxRows {
				break
			}

			tcpFamily := 4
			if event.Family == syscall.AF_INET6 {
				tcpFamily = 6
			}

			fmt.Printf("%-16s %-16s %-16s %-16s %-7d %-16s %-3d %-51s %-51s %-7d %d\n",
				event.Node, event.Namespace, event.Pod, event.Container,
				event.Pid, event.Comm, tcpFamily,
				fmt.Sprintf("%s:%d", event.Saddr, event.Sport),
				fmt.Sprintf("%s:%d", event.Daddr, event.Dport),
				event.Received/1048, event.Sent/1048)
		}
	case utils.OutputModeJSON:
		b, err := json.Marshal(stats)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error marshalling json: %v", err)
			return
		}
		fmt.Println(string(b))
	case utils.OutputModeCustomColumns:
		for idx, stat := range stats {
			if idx == maxRows {
				break
			}
			fmt.Println(tcpFormatEventCustomCols(&stat, params.CustomColumns))
		}
	}
}

func tcpGetCustomColsHeaders(cols []string) string {
	var sb strings.Builder

	for _, col := range cols {
		switch col {
		case "node":
			sb.WriteString(fmt.Sprintf("%-16s", "NODE"))
		case "namespace":
			sb.WriteString(fmt.Sprintf("%-16s", "NAMESPACE"))
		case "pod":
			sb.WriteString(fmt.Sprintf("%-16s", "POD"))
		case "container":
			sb.WriteString(fmt.Sprintf("%-16s", "CONTAINER"))
		case "pid":
			sb.WriteString(fmt.Sprintf("%-7s", "PID"))
		case "comm":
			sb.WriteString(fmt.Sprintf("%-16s", "COMM"))
		case "family":
			sb.WriteString(fmt.Sprintf("%-3s", "IPv"))
		case "saddr":
			sb.WriteString(fmt.Sprintf("%-51s", "LADDR"))
		case "daddr":
			sb.WriteString(fmt.Sprintf("%-51s", "DADDR"))
		case "sent":
			sb.WriteString(fmt.Sprintf("%-7s", "TX_KB"))
		case "received":
			sb.WriteString(fmt.Sprintf("%-7s", "RX_KB"))
		}
		sb.WriteRune(' ')
	}

	return sb.String()
}

func tcpFormatEventCustomCols(stats *types.Stats, cols []string) string {
	var sb strings.Builder

	for _, col := range cols {
		switch col {
		case "node":
			sb.WriteString(fmt.Sprintf("%-16s", stats.Node))
		case "namespace":
			sb.WriteString(fmt.Sprintf("%-16s", stats.Namespace))
		case "pod":
			sb.WriteString(fmt.Sprintf("%-16s", stats.Pod))
		case "container":
			sb.WriteString(fmt.Sprintf("%-16s", stats.Container))
		case "pid":
			sb.WriteString(fmt.Sprintf("%-7d", stats.Pid))
		case "comm":
			sb.WriteString(fmt.Sprintf("%-16s", stats.Comm))
		case "family":
			tcpFamily := 4
			if stats.Family == syscall.AF_INET6 {
				tcpFamily = 6
			}

			sb.WriteString(fmt.Sprintf("%-3d", tcpFamily))
		case "saddr":
			sb.WriteString(fmt.Sprintf("%-51s", fmt.Sprintf("%s:%d", stats.Saddr, stats.Sport)))
		case "daddr":
			sb.WriteString(fmt.Sprintf("%-51s", fmt.Sprintf("%s:%d", stats.Daddr, stats.Dport)))
		case "sent":
			sb.WriteString(fmt.Sprintf("%-7d", stats.Sent))
		case "received":
			sb.WriteString(fmt.Sprintf("%d", stats.Received))
		}
		sb.WriteRune(' ')
	}

	return sb.String()
}
