// Copyright 2019-2021 The Inspektor Gadget authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package top

import (
	"fmt"
	"strconv"

	"github.com/spf13/cobra"

	commonutils "github.com/inspektor-gadget/inspektor-gadget/cmd/common/utils"
	"github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/top"
	"github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/top/tcp/types"
)

func newTCPCmd() *cobra.Command {
	var commonTopFlags CommonTopFlags

	var (
		filteredPid uint
		family      uint
	)

	cols := types.GetColumns()

	cmd := &cobra.Command{
		Use:   fmt.Sprintf("tcp [interval=%d]", top.IntervalDefault),
		Short: "Periodically report TCP activity",
		RunE: func(cmd *cobra.Command, args []string) error {
			parser, err := commonutils.NewGadgetParserWithK8sInfo(&commonTopFlags.OutputConfig, types.GetColumns())
			if err != nil {
				return commonutils.WrapInErrParserCreate(err)
			}

			parameters := make(map[string]string)
			if family != 0 {
				parameters[types.FamilyParam] = strconv.FormatUint(uint64(family), 10)
			}
			if filteredPid != 0 {
				parameters[types.PidParam] = strconv.FormatUint(uint64(filteredPid), 10)
			}

			gadget := &TopGadget[types.Stats]{
				name:           "tcptop",
				commonTopFlags: &commonTopFlags,
				params:         parameters,
				parser:         parser,
				nodeStats:      make(map[string][]*types.Stats),
				colMap:         cols.GetColumnMap(),
			}

			return gadget.Run(args)
		},
		SilenceUsage: true,
		Args:         cobra.MaximumNArgs(1),
	}

	addCommonTopFlags(cmd, &commonTopFlags, &commonTopFlags.CommonFlags, cols.ColumnMap, types.SortByDefault)

	cmd.PersistentFlags().UintVarP(
		&filteredPid,
		"pid",
		"",
		0,
		"Show only TCP events generated by this particular PID",
	)
	cmd.PersistentFlags().UintVarP(
		&family,
		"family",
		"f",
		0,
		"Show only TCP events for this IP version: either 4 or 6 (by default all will be printed)",
	)

	return cmd
}
