modifiedFilesOnly: true
reporter: github-pr-check
useGitIgnore: true
fileExtensions:
  - md
  - mdx
  - txt
replacementPatterns:
  - pattern: '%IG_BRANCH%'
    replacement: 'main'
  - pattern: '%IG_TAG%'
    replacement: 'latest'
