all: ldpreload oteltarball

ldpreload:
	make -C container-ldpreload

oteltarball:
	#rm -f otel.tar.gz
	#tar czf otel.tar.gz -C ../../../lightstep/opentelemetry-auto-instr-python/ oteltracepy
	touch otel.tar.gz
