#!/bin/bash

if grep -q '^ID=flatcar$' /host/etc/os-release > /dev/null ; then
  if grep -q '^GROUP=edge$' /host/etc/flatcar/update.conf > /dev/null ; then
    exit 0
  fi
fi

echo "Gadget not available." >&2
exit 1
