apiVersion: 1
kind: instance-spec
image: trace_dns:latest
name: failed-dns-requests-all
paramValues:
  operator.KubeManager.all-namespaces: true
  operator.filter.filter: rcode!=Success,qr==R
  operator.cli.fields: k8s.namespace,k8s.podname,src,dst,name,rcode
