apiVersion: 1
kind: instance-spec
image: trace_exec:latest
name: modified-files-all
paramValues:
  operator.KubeManager.all-namespaces: true
  operator.filter.filter: upper_layer==true
  operator.cli.output: jsonpretty
