// Copyright 2026 The Inspektor Gadget authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Command generate-catalog scans the gadgets/ directory and produces the
// default gadget catalog consumed by the Helm chart
// (charts/gadget/files/catalog.yaml). It is run via `make generate-catalog`.
//
// The catalog is discovery-only metadata: each entry exposes the gadget's short
// image name, a display name, a description and a set of tags. Tags are derived
// deterministically from the gadget's directory name (split on "_") plus its
// category, so the file can always be regenerated from the gadgets metadata.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// gadgetMetadata is the subset of gadget.yaml fields relevant to the catalog.
type gadgetMetadata struct {
	Name        string   `yaml:"name"`
	Category    string   `yaml:"category"`
	Description string   `yaml:"description"`
	Tags        []string `yaml:"tags"`
}

// catalogEntry mirrors the structure expected by the Helm chart and the server.
type catalogEntry struct {
	Gadget      string
	Description string
	Tags        []string
}

// skipDirs are directories under gadgets/ that are not user-facing gadgets.
var skipDirs = map[string]bool{
	"ci":      true,
	"testing": true,
}

func main() {
	gadgetsDir := flag.String("gadgets-dir", "gadgets", "path to the gadgets directory")
	output := flag.String("output", filepath.Join("charts", "gadget", "files", "catalog.yaml"),
		"path to the generated catalog file")
	flag.Parse()

	entries, err := collectEntries(*gadgetsDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "collecting catalog entries: %v\n", err)
		os.Exit(1)
	}

	if err := writeCatalog(*output, entries); err != nil {
		fmt.Fprintf(os.Stderr, "writing catalog: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("wrote %d catalog entries to %s\n", len(entries), *output)
}

func collectEntries(gadgetsDir string) ([]catalogEntry, error) {
	dirEntries, err := os.ReadDir(gadgetsDir)
	if err != nil {
		return nil, fmt.Errorf("reading gadgets directory %q: %w", gadgetsDir, err)
	}

	var entries []catalogEntry
	for _, de := range dirEntries {
		if !de.IsDir() || skipDirs[de.Name()] {
			continue
		}

		metadataPath := filepath.Join(gadgetsDir, de.Name(), "gadget.yaml")
		data, err := os.ReadFile(metadataPath)
		if err != nil {
			if os.IsNotExist(err) {
				// Not every directory is a gadget (e.g. shared helpers).
				continue
			}
			return nil, fmt.Errorf("reading %q: %w", metadataPath, err)
		}

		var md gadgetMetadata
		if err := yaml.Unmarshal(data, &md); err != nil {
			return nil, fmt.Errorf("parsing %q: %w", metadataPath, err)
		}

		entries = append(entries, catalogEntry{
			Gadget:      de.Name(),
			Description: strings.TrimSpace(md.Description),
			Tags:        deriveTags(de.Name(), md.Category, md.Tags),
		})
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Gadget < entries[j].Gadget
	})
	return entries, nil
}

// deriveTags builds a deterministic tag list for a gadget. It combines tags
// derived from the gadget directory name (split on "_"), the gadget category,
// and any explicit tags declared in the gadget's metadata (gadget.yaml `tags`).
// The result is de-duplicated while preserving order: name parts first, then
// category, then explicit tags.
func deriveTags(dir, category string, explicit []string) []string {
	var tags []string
	add := func(t string) {
		t = strings.TrimSpace(t)
		if t != "" && !slices.Contains(tags, t) {
			tags = append(tags, t)
		}
	}

	for _, part := range strings.Split(dir, "_") {
		add(part)
	}
	add(category)
	for _, t := range explicit {
		add(t)
	}
	return tags
}

func writeCatalog(output string, entries []catalogEntry) error {
	var buf bytes.Buffer
	buf.WriteString("# This file is generated by 'make generate-catalog'; DO NOT EDIT.\n")
	buf.WriteString("# It contains the default, discovery-only catalog of official gadgets\n")
	buf.WriteString("# exposed to clients via `catalog list`.\n")

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)

	// Encode as a list of maps so that field ordering is stable and readable.
	list := make([]yaml.Node, 0, len(entries))
	for _, e := range entries {
		list = append(list, entryNode(e))
	}
	root := yaml.Node{Kind: yaml.SequenceNode, Content: nodePointers(list)}
	if err := enc.Encode(&root); err != nil {
		return fmt.Errorf("encoding catalog: %w", err)
	}
	if err := enc.Close(); err != nil {
		return fmt.Errorf("closing encoder: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}
	if err := os.WriteFile(output, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("writing %q: %w", output, err)
	}
	return nil
}

func entryNode(e catalogEntry) yaml.Node {
	m := &yaml.Node{Kind: yaml.MappingNode}
	addScalar(m, "gadget", e.Gadget)
	if e.Description != "" {
		addScalar(m, "description", e.Description)
	}
	if len(e.Tags) > 0 {
		seq := &yaml.Node{Kind: yaml.SequenceNode}
		for _, t := range e.Tags {
			seq.Content = append(seq.Content, &yaml.Node{Kind: yaml.ScalarNode, Value: t})
		}
		m.Content = append(m.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: "tags"},
			seq,
		)
	}
	return *m
}

func addScalar(m *yaml.Node, key, value string) {
	m.Content = append(m.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: key},
		&yaml.Node{Kind: yaml.ScalarNode, Value: value},
	)
}

func nodePointers(nodes []yaml.Node) []*yaml.Node {
	ptrs := make([]*yaml.Node, len(nodes))
	for i := range nodes {
		ptrs[i] = &nodes[i]
	}
	return ptrs
}
