apiVersion: v1
kind: Pod
metadata:
  name: hello-python
  namespace: seccomp-demo
  labels:
    app: hello-python
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: operator/seccomp-demo/hello-profile.json
  containers:
  - name: hello-python
    image: tiangolo/uwsgi-nginx-flask:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    volumeMounts:
    - name: app-script
      mountPath: /app/
  volumes:
  - name: app-script
    configMap:
      name: app-script
