kind: Namespace
apiVersion: v1
metadata:
  name: gadget-test
  labels:
    name: gadget-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gadget-test
  namespace: gadget-test
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gadget-test
subjects:
- kind: ServiceAccount
  name: gadget-test
  namespace: gadget-test
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: gadget-test
  namespace: gadget-test
spec:
  template:
    spec:
      serviceAccount: gadget-test
      containers:
      - name: gadget-test
        image: ghcr.io/kinvolk/inspektor-gadgettest:latest
        imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 0
