// Copyright 2022-2023 The Inspektor Gadget authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package tracer

import (
	"github.com/inspektor-gadget/inspektor-gadget/internal/parser"
	gadgetregistry "github.com/inspektor-gadget/inspektor-gadget/pkg/gadget-registry"
	"github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets"
	"github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/top/tcp/types"
	"github.com/inspektor-gadget/inspektor-gadget/pkg/params"
)

type gadget struct {
	*gadgets.GadgetWithParams
}

func (g *gadget) Name() string {
	return "tcp"
}

func (g *gadget) Category() string {
	return gadgets.CategoryTop
}

func (g *gadget) Type() gadgets.GadgetType {
	return gadgets.TypeTraceIntervals
}

func (g *gadget) Description() string {
	return "Periodically report TCP activity"
}

func (g *gadget) Parser() parser.Parser {
	return parser.NewParser(types.GetColumns())
}

func (g *gadget) EventPrototype() any {
	return &types.Stats{}
}

func (g *gadget) SortByDefault() []string {
	return types.SortByDefault
}

func NewGadget() *gadget {
	paramsDescs := &params.ParamDescs{
		{
			Key:          types.PidParam,
			Title:        "PID",
			Description:  "Show only TCP events generated by this particular PID (-1 for all)",
			DefaultValue: "-1",
			TypeHint:     params.TypeInt,
		},
		{
			Key:            types.FamilyParam,
			Alias:          "f",
			DefaultValue:   "all",
			Description:    "Show only TCP events for this IP version: either 4 or 6 (by default all will be printed)",
			PossibleValues: []string{"all", "4", "6"},
		},
	}
	return &gadget{
		GadgetWithParams: gadgets.NewGadgetWithParams(paramsDescs),
	}
}

func init() {
	gadgetregistry.RegisterGadget(NewGadget())
}
