// Copyright 2022 The Inspektor Gadget authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this tcp except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package top

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/top"
)

type TCPFlags struct {
	CommonTopFlags

	FilteredPid uint
	Family      uint
}

func NewTCPCmd(runCmd func(*cobra.Command, []string) error, flags *TCPFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   fmt.Sprintf("tcp [interval=%d]", top.IntervalDefault),
		Short: "Periodically report TCP activity",
		RunE:  runCmd,
		Args:  cobra.MaximumNArgs(1),
	}

	cmd.PersistentFlags().UintVarP(&flags.FilteredPid, "pid", "", 0, "Show only TCP events generated by this particular PID")
	cmd.PersistentFlags().UintVarP(&flags.Family, "family", "f", 0, "Show only TCP events for this IP version: either 4 or 6 (by default all will be printed)")

	return cmd
}
