name: Inspektor Gadget Debug
on:
  workflow_dispatch:

permissions: write-all

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Setup tmate session
      env:
        GH_TOKEN: ${{ github.token }}
      uses: mxschmitt/action-tmate@v3
