name: Inspektor Gadget Debug
env:
  REGISTRY: ghcr.io
  CONTAINER_REPO: ${{ github.repository_owner }}
  GO_VERSION: 1.24.2

on:
  push:

permissions: write-all

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: imjasonh/setup-crane@31b88efe9de28ae0ffa220711af4b60be9435f6e # v0.4
    - name: Setup tmate session
      env:
        GH_TOKEN: ${{ github.token }}
      uses: mxschmitt/action-tmate@v3
